export const RealityState = Object.freeze({
  EVIDENCE_READY: 'EVIDENCE_READY',
  VERIFIED: 'VERIFIED',
  CONTRADICTED: 'CONTRADICTED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  HUMAN_REVIEW_REQUIRED: 'HUMAN_REVIEW_REQUIRED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ACTION_AUTHORIZED: 'ACTION_AUTHORIZED',
  ACTION_EXECUTED: 'ACTION_EXECUTED',
  EXECUTION_DIVERGED: 'EXECUTION_DIVERGED',
  RECEIPT_ISSUED: 'RECEIPT_ISSUED'
});

export const OperationResult = Object.freeze({
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  UNKNOWN: 'UNKNOWN',
  RETRYING: 'RETRYING',
  WAITING: 'WAITING',
  AWAITING_APPROVAL: 'AWAITING_APPROVAL',
  CANCELLED: 'CANCELLED'
});
